[firebase_client]
"apiKey"="AIzaSyAxHp_qQ0MmlMANICIg9c_wZ9yJX5EG6cE"
"authDomain"="foodprj.firebaseapp.com"
"databaseURL"="https://foodprj-default-rtdb.asia-southeast1.firebasedatabase.app"
"projectId"="foodprj"
"storageBucket"="foodprj.firebasestorage.app"
"messagingSenderId"="109233219921"
"appId"="1:109233219921:web:05e8fe84a73b84977f0b70"
"measurementId"="G-E0F4XW3JBJ"

[firebase_admin]
"type"="service_account" 
"project_id" = "foodprj" 
"private_key_id" = "acb026f1ff9c25942516fe84b876918f9541bbe5" 
"private_key" = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCjd4Y1lxH2Dohs\nacpr1OYstPnlOqnfHCS/SxlGlxNXkXmAtfGI/WPPzcE8q5/Zqpb5ZIgxNrulbnmQ\nyfSHf8hpyoODjKL41e2HoR+BTQ64O/gkkQqku1tWvor3/nn8hMH1EsgF66lk0wpa\nZv6oHA5lrSm6vSHRUFVkNsI8wm0E6duLd4AsikUqjW2X0hDajeMaS9Cent/0i+jZ\nb7xKoD98BFJReWYT+LRTKr+6hxFouBM14wVDyee6CgDuyUSikj848mNgHamBgypD\nBEh9ttAkgbIngSE8z37vzqfxcUPqhWDEZPUCv4F3UaGjGq+XwMx3R+BehNE0riZS\nhSISplCjAgMBAAECgf9yTCCLWBY29fJt24qt2y8WE3Sn01zzo7oOB3Sk5v2fPRi3\n5n/8STCBHF0BDv+2MpFdz+1qe9q40YYutwdDtxVq4y8RzEQnuW1caEyfHEIuj7/x\n0XiftmEnRhPlUwn4htsXgQpbGWxYEzgp/doRsYxfi7Sh3ZzHvmP2rlMiKNARnlTK\nLlbIa4ix7hadgrNmiLADYClqZKqUcABL1uF/vT2BLIZl4aGACGK7kjrdRpR/D1iv\nisPvbAPYHQYD+u6spm5Ee/CGXD0bQIJCkR/CkZJTD6a6HejFu03xdmYul3JRwgTX\nGNR8WddCm8oRsYlWbIFDU93c3WvtJDc/LFB4YKkCgYEAz3FEPt6dwK7FP3bCuvyZ\n93h0iqdsLRWeh4iAW0wh6ZUBHLMhTn0cytEMqNG/EejOB8yN34Vy7EjKu6Hogn9P\nICXfvPeLs4/h19Jn3R+R43a1PK+Fu9gayqlOZcbi1gg/YxtCFeSOLAundafADLem\n4f1bm2PW7A9hl5tHOXgHfdcCgYEAybsTm3TiDZ1xP/ECAwth6tmG7wYi2YYbvqhn\nQnoIASx/l3twXR80vvBNVqTXGCN32yZGM1zSDDlJeJoaCiPb/7qGMo1TXxvVW7gC\n15fKWYZHfOwoQF4RjiA4Qqy3AVGIuZZg1yI5cpR/Minb6lbcpNiNsWZTY0yJ2fWc\n7WeTMhUCgYEAyn0hxMzA6CixWbWvd57DHBF0kTPEIG4OBPZ1dKjoIX3VTBJ+3IK7\n7C4LUW8MN4ssMei2RA2blJGpc2Yj894ZeqP9thNdRrWYGnfD8tCyM3rYhpg+zpGv\n9Us2v5pYKdx7I16kL4KeVNg7almI2eEbAVWyaggW7u5EsRxddfd4OJkCgYBED3Dz\nDwFBdLAD0a1LF6kGkjN7K0fQufVcYvbLr95JfxjhI81qLaAfF3YQWHcVdsn2Tzh6\nFcPsSdum698DMswDwIuMPLA3M23NjwyublDf2XT/CbIe3V3w5J/2pszrjfWiH8E2\ndB6LsNwlMYg3zOyOVV2gz5QsuWL8/WfflQVNbQKBgQDICjaHHq0aoYMD134l8/La\nbNf3aUgDEWbsu899zSfxGhy+fyvza5nud0oIE1Mm/A1o7ZzBd3OXJAu2pubT6+Xu\nGDiVhPFzuVURRB8OnIN+UgjYLJP+NLatOxAyFs+fM67AGbsu2sFumL2qb0B2I5dp\nAkSPMwuw7HI1IYjP/RpO/Q==\n-----END PRIVATE KEY-----\n" 
"client_email" = "firebase-adminsdk-fbsvc@foodprj.iam.gserviceaccount.com" 
"client_id" = "111841622666920241795" 
"auth_uri" = "https://accounts.google.com/o/oauth2/auth" 
"token_uri"= "https://oauth2.googleapis.com/token" 
"auth_provider_x509_cert_url"= "https://www.googleapis.com/oauth2/v1/certs" 
"client_x509_cert_url"= "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40foodprj.iam.gserviceaccount.com" 
"universe_domain"= "googleapis.com"
